### PR TITLE
Multiple backwards-compatible fixes

### PR DESCRIPTION
**Pull request by kostyrev**
* Add molecule support for role testing purposes
* Add ability to override comment
* Add ability to specify group other than username
* Make specifying uid optional
* Add toggle to optionally upload ssh keys
* Add toggle to optionally create usergroup
* Update README.md regarding usergroup creation

Build log is [here](https://travis-ci.org/kostyrevaa/ansible_users)

### CODE REVIEW

**Comment by kostyrev** [comment]
pinging @hudecof just in case

**Comment by hudecof** [comment]
@kostyrevaa thanks for update. I see the `playbook.yml` in files you added. Are you it should be there?

**Comment by kostyrev** [comment]
Yep, [molecule](https://molecule.readthedocs.io) uses it.
I put there many code paths to test.

**Comment by kostyrev** [comment]
Hi @hudecof 
Thanks for merging.
I'd like to point out that you should direct build badge to you repo instead of my fork.

**Pull request merged**
